In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./tap_fun_train.csv')

In [9]:
df2 = df[['wood_add_value', 'wood_reduce_value',
       'stone_add_value', 'stone_reduce_value', 'ivory_add_value',
       'ivory_reduce_value', 'meat_add_value', 'meat_reduce_value','pve_battle_count', 'pve_lanch_count', 'pve_win_count',
       'avg_online_minutes', 'pay_price', 'pay_count']]

In [10]:
df.columns

Index(['user_id', 'register_time', 'wood_add_value', 'wood_reduce_value',
       'stone_add_value', 'stone_reduce_value', 'ivory_add_value',
       'ivory_reduce_value', 'meat_add_value', 'meat_reduce_value',
       ...
       'pvp_battle_count', 'pvp_lanch_count', 'pvp_win_count',
       'pve_battle_count', 'pve_lanch_count', 'pve_win_count',
       'avg_online_minutes', 'pay_price', 'pay_count', 'prediction_pay_price'],
      dtype='object', length=109)

In [11]:
df.prediction_pay_price[df['prediction_pay_price']!=0]

25            0.99
40            4.96
47           12.97
86            0.99
119           0.99
155         166.86
171          26.94
214           9.99
248          19.97
305           0.99
380           1.98
381        8982.78
390           0.99
434           0.99
450          16.96
481           8.96
562          15.97
616        1858.58
617         167.73
625           0.99
630          10.97
643           1.98
716           0.99
726           0.99
817           1.98
835           0.99
845           0.99
981           5.98
982           0.99
1004          1.98
            ...
2286871       4.99
2286913       0.99
2286961      76.89
2286987       4.97
2287028       0.99
2287109      10.95
2287140       6.97
2287179       6.97
2287262     256.83
2287373     306.79
2287410      21.93
2287492       0.99
2287517    2962.51
2287520       0.99
2287555      17.96
2287618      84.86
2287629       0.99
2287668       0.99
2287708       1.98
2287712      58.89
2287742       0.99
2287780       4.99
2287839      26.95
2287863      73.87
2287876      56.89
2287944       0.99
2287946     932.33
2287960      20.96
2287970       0.99
2287984       1.98
Name: prediction_pay_price, Length: 45988, dtype: float64

In [12]:
from sklearn.linear_model import LinearRegression

In [26]:
model = LinearRegression(normalize=True)

In [27]:
model.fit(df2,df.prediction_pay_price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=True)

In [28]:
train_score = model.score(df2,df.prediction_pay_price)

In [29]:
train_score

0.5516736287020352

In [17]:
test = pd.read_csv('./tap_fun_test.csv')

In [18]:
test

,user_id,register_time,wood_add_value,wood_reduce_value,stone_add_value,stone_reduce_value,ivory_add_value,ivory_reduce_value,meat_add_value,meat_reduce_value,...,sr_rss_help_bonus_level,pvp_battle_count,pvp_lanch_count,pvp_win_count,pve_battle_count,pve_lanch_count,pve_win_count,avg_online_minutes,pay_price,pay_count
0,14933,2018-03-08 20:27:57,166415.0,138362.0,0,0,0,0,258522,90142,...,0,0,0,0,1,1,1,8.000000,0.00,0
1,14934,2018-03-08 20:29:42,10000.0,600.0,0,0,0,0,10000,400,...,0,0,0,0,0,0,0,0.166667,0.00,0
2,14935,2018-03-08 20:30:13,10000.0,3700.0,0,0,0,0,10000,2000,...,0,0,0,0,0,0,0,17.000000,0.00,0
3,14936,2018-03-08 20:31:41,210000.0,0.0,200000,0,200000,0,610000,0,...,0,0,0,0,0,0,0,1.666667,0.00,0
4,14937,2018-03-08 20:32:07,11500.0,3700.0,0,0,0,0,11000,2000,...,0,0,0,0,0,0,0,0.333333,0.00,0
5,14938,2018-03-08 20:33:24,10000.0,0.0,0,0,0,0,10000,0,...,0,0,0,0,0,0,0,0.000000,0.00,0
6,14939,2018-03-08 20:34:04,46088.0,20820.0,0,0,0,0,42650,11630,...,0,0,0,0,0,0,0,21.833333,0.00,0
7,14940,2018-03-08 20:34:41,10000.0,600.0,0,0,0,0,10000,400,...,0,0,0,0,0,0,0,0.166667,0.00,0
8,14941,2018-03-08 20:35:27,308065.0,205590.0,0,0,0,0,289387,109013,...,0,6,3,0,2,2,2,8.000000,0.00,0
9,14942,2018-03-08 20:37:12,27688.0,5750.0,0,0,0,0,32625,3000,...,0,0,0,0,0,0,0,0.500000,0.00,0
10,14943,2018-03-08 20:39:48,38538.0,8830.0,0,0,0,0,42051,6220,...,0,0,0,0,1,1,1,0.833333,0.00,0
11,14944,2018-03-08 20:40:20,11500.0,3700.0,0,0,0,0,11000,2000,...,0,0,0,0,0,0,0,0.333333,0.00,0
12,14945,2018-03-08 20:42:15,46018.0,21834.0,0,0,0,0,40090,11592,...,0,0,0,0,0,0,0,0.833333,0.00,0
13,14946,2018-03-08 20:43:13,228125.0,3700.0,200000,0,200000,0,633375,2000,...,0,0,0,0,0,0,0,0.500000,0.00,0
14,14947,2018-03-08 20:47:03,142028.0,73906.0,0,0,0,0,133463,58255,...,0,1,0,0,1,1,1,7.166667,0.00,0
15,14948,2018-03-08 20:49:18,127944.0,59734.0,0,0,0,0,126620,37475,...,0,2,1,0,1,1,1,3.500000,0.00,0
16,14949,2018-03-08 20:49:17,141781.0,93524.0,0,0,0,0,114418,59973,...,0,1,1,0,1,1,1,2.833333,0.00,0
17,14950,2018-03-08 20:49:19,86386.0,37134.0,0,0,0,0,72152,21789,...,0,0,0,0,1,1,1,2.500000,0.00,0
18,14951,2018-03-08 20:50:13,664810.0,448867.0,20000,0,3000,0,651451,374909,...,0,2,0,0,3,3,3,17.833333,0.00,0
19,14952,2018-03-08 20:51:27,3838322.0,2859288.0,1041000,0,504000,0,6898146,4297996,...,0,4,4,4,4,4,3,27.166667,0.99,1
20,14953,2018-03-08 20:51:30,15500.0,3700.0,0,0,0,0,13000,2000,...,0,0,0,0,0,0,0,0.333333,0.00,0
21,14954,2018-03-08 20:52:42,37038.0,17280.0,0,0,0,0,38056,10820,...,0,0,0,0,0,0,0,2.166667,0.00,0
22,14955,2018-03-08 20:53:55,39601.0,9830.0,0,0,0,0,189306,6945,...,0,0,0,0,0,0,0,1.500000,0.00,0
23,14956,2018-03-08 20:55:25,26375.0,5200.0,0,0,0,0,32000,2750,...,0,0,0,0,0,0,0,0.666667,0.00,0
24,14957,2018-03-08 20:55:29,51939.0,15760.0,0,0,3000,0,50253,10000,...,0,0,0,0,1,1,1,1.333333,0.00,0
25,14958,2018-03-08 20:56:26,11500.0,3700.0,0,0,0,0,11000,2000,...,0,0,0,0,0,0,0,0.333333,0.00,0
26,14959,2018-03-08 20:57:42,43164.0,11780.0,0,0,0,0,45167,8070,...,0,0,0,0,1,1,1,1.000000,0.00,0
27,14960,2018-03-08 20:58:41,808822.0,510951.0,200000,0,200000,0,1491978,822008,...,0,4,3,2,2,2,2,8.000000,0.00,0
28,14961,2018-03-08 20:59:21,148154.0,49501.0,0,0,3000,0,101561,32658,...,0,0,0,0,1,1,1,1.833333,0.00,0
29,14962,2018-03-08 20:59:27,123487.0,44345.0,0,0,0,0,97278,28306,...,0,0,0,0,1,1,1,2.333333,0.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828904,3176514,2018-03-07 02:17:21,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.000000,0.00,0
828905,3176515,2018-03-07 02:17:35,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.000000,0.00,0
828906,3176516,2018-03-07 02:18:39,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.666667,0.00,0
828907,3176517,2018-03-07 02:19:21,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.000000,0.00,0
828908,3176518,2018-03-07 02:22:15,96783.0,64304.0,0,0,6000,0,122397,40841,...,0,0,0,0,4,4,3,5.833333,0.00,0
828909,3176519,2018-03-07 02:23:39,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.333333,0.00,0
828910,3176520,2018-03-07 02:24:21,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.166667,0.00,0
828911,3176521,2018-03-07 02:27:40,294709.0,152723.0,0,0,0,0,252064,136906,...,0,5,0,1,2,2,1,12.833333,0.00,0
828912,3176522,2018-03-07 02:27:56,80342.0,17349.0,0,0,0,0,55067,12732,...,0,0,0,0,1,1,1,3.333333,0.00,0
828913,3176523,2018-03-07 02:30:00,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.500000,0.00,0
828914,3176524,2018-03-07 02:30:14,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.666667,0.00,0
828915,3176525,2018-03-07 02:31:10,50000.0,6804.0,0,0,0,0,0,3564,...,0,0,0,0,0,0,0,2.000000,0.00,0
828916,3176526,2018-03-07 02:31:34,55249.0,26207.0,0,0,3000,0,6754,23566,...,0,3,0,0,1,1,1,5.000000,0.00,0
828917,3176527,2018-03-07 02:34:39,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.000000,0.00,0
828918,3176528,2018-03-07 02:35:03,60153.0,24224.0,0,0,3000,0,7331,19142,...,0,1,0,0,1,1,1,3.000000,0.00,0
828919,3176529,2018-03-07 02:35:25,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.166667,0.00,0
828920,3176530,2018-03-07 02:36:50,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.666667,0.00,0
828921,3176531,2018-03-07 02:41:33,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2.500000,0.00,0
828922,3176532,2018-03-07 02:43:31,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.500000,0.00,0
828923,3176533,2018-03-07 02:45:07,217646.0,152491.0,0,0,0,0,339196,124698,...,0,0,0,0,4,4,2,14.666667,0.00,0
828924,3176534,2018-03-07 02:45:58,190217.0,110202.0,0,0,3000,0,119366,89690,...,0,15,12,6,2,2,2,8.500000,0.00,0
828925,3176535,2018-03-07 02:55:46,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.500000,0.00,0
828926,3176536,2018-03-07 02:56:29,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2.500000,0.00,0
828927,3176537,2018-03-07 02:56:45,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.166667,0.00,0
828928,3176538,2018-03-07 02:57:33,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.166667,0.00,0
828929,3176539,2018-03-07 02:58:13,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2.333333,0.00,0
828930,3176540,2018-03-07 02:58:51,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.833333,0.00,0
828931,3176541,2018-03-07 02:59:47,151732.0,66946.0,0,0,0,0,96776,51906,...,0,4,2,1,0,0,0,6.666667,0.00,0
828932,3176542,2018-03-07 03:00:11,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.833333,0.00,0
828933,3176543,2018-03-07 03:00:34,0.0,0.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,7.333333,0.00,0

In [19]:
test_pre = model.predict(test[['wood_add_value', 'wood_reduce_value',
       'stone_add_value', 'stone_reduce_value', 'ivory_add_value',
       'ivory_reduce_value', 'meat_add_value', 'meat_reduce_value','pve_battle_count', 'pve_lanch_count', 'pve_win_count',
       'avg_online_minutes', 'pay_price', 'pay_count']])

In [20]:
test_pre[test_pre<0]=0

In [21]:
test_pre

array([0.        , 0.        , 0.18954677, ..., 0.        , 0.        ,
       0.03683288])

In [22]:
dfsa1 = pd.DataFrame()
dfsa1['user_id']= test.user_id
dfsa1['prediction_pay_price'] = test_pre

In [23]:
dfsa1 = dfsa1[['user_id','prediction_pay_price']]

In [24]:
test_pre.sum()

2440718.139248454

In [25]:
dfsa1.to_csv('./tap4_20180621_2323.csv',index=False)